#!/usr/bin/env zsh

dotfiles=~/dotfiles

ln -sf $dotfiles/zshrc ~/.zshrc
ln -sfn $dotfiles/nvim ~/.config/nvim

if [[ ! -d ~/.tmux/plugins/tpm ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

ln -sf $dotfiles/tmux.conf ~/.tmux.conf
